<MainMenu>
    BoxLayout:
        orientation: 'vertical'
        size: root.size

        TabbedPanel:
            do_default_tab: False
            tab_width: 300

            TabbedPanelItem:
                id: edit
                text: '取り込み/編集'
                EditContainer:

            TabbedPanelItem:
                id: offprocess
                text: 'オフライン信号処理'
                OffprocessContainer:
                    id: offprocess_container
